package io.github.rektroth.whiteout.mixin.mc108513;

import io.github.rektroth.whiteout.accessors.GeneratedByDragonFightAccessor;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.dimension.end.DragonRespawnStage;
import net.minecraft.world.level.storage.ValueInput;
import net.minecraft.world.level.storage.ValueOutput;
import org.jetbrains.annotations.Nullable;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.Shadow;
import org.spongepowered.asm.mixin.Unique;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * End crystal modifications for MC-108513 patch.
 */
@Mixin(EndCrystal.class)
public abstract class EndCrystalEntityMixin extends Entity implements GeneratedByDragonFightAccessor {
    /**
     * Whether the end crystal was generated by the dragon fight.
     */
    @Unique
    public boolean generatedByDragonFight = false;

    /**
     * Sets the target of the end crystal's beam.
     * @param beamTarget The target to set the beam toward.
     */
    @Shadow
    public abstract void setBeamTarget(@Nullable BlockPos beamTarget);

    /**
     * boilerplate
     * @param type  boilerplate
     * @param level boilerplate
     */
    public EndCrystalEntityMixin(EntityType<?> type, Level level) {
        super(type, level);
    }

    /**
     * Sets the `setGeneratedByDragonFight` property.
     * @param generatedByDragonFight Whether the end crystal was generated by the dragon fight.
     */
    @Unique
    public void whiteout$setGeneratedByDragonFight(boolean generatedByDragonFight) {
        this.generatedByDragonFight = generatedByDragonFight;
    }

    /**
     * Modifies the method to only tick the crystal as "invulnerable" if was both created by the ender dragon fight
     * and the ender dragon fight is either in progress or being summoned.
     * @param ci boilerplate
     */
    @Inject(at = @At("TAIL"), method = "tick")
    private void tickNotInvulnerable(CallbackInfo ci) {
        if (this.generatedByDragonFight && this.isInvulnerable()) {
            // I can't figure out what `uuid` and `getOriginalWorld()` map to in Fabric
            // It might be possible that 1.20.5 got rid of them entirely?
            // Will want to check how Paper modified this function after they update
            // The fix as-is will still prevent most common exploits
            if (/*!Objects.equals(((ServerWorld)this.getWorld()).uuid, this.getOriginWorld())
                ||*/ ((ServerLevel)this.level()).getDragonFight() == null
                || ((EnderDragonFightAccessor)((ServerLevel)this.level()).getDragonFight()).getRespawnStage() == null
                || ((EnderDragonFightAccessor)((ServerLevel)this.level()).getDragonFight()).getRespawnStage().ordinal() > DragonRespawnStage.SUMMONING_DRAGON.ordinal()
            ) {
                this.setInvulnerable(false);
                this.setBeamTarget(null);
            }
        }
    }

    // Prefixing the custom NBT data with "Paper" instead of "Whiteout" makes this fix cross-compatible with Paper worlds

    /**
     * Writes "GeneratedByDragonFight" property to NBT.
     * @param output The NBT values.
     * @param ci     boilerplate
     */
    @Inject(at = @At("TAIL"), method = "addAdditionalSaveData")
    private void writeGeneratedByDragonFightToNbt(ValueOutput output, CallbackInfo ci) {
        output.putBoolean("Paper.GeneratedByDragonFight", this.generatedByDragonFight);
    }

    /**
     * Reads "GeneratedByDragonFight" property from NBT.
     * @param input The NBT values.
     * @param ci    boilerplate
     */
    @Inject(at = @At("TAIL"), method = "readAdditionalSaveData")
    private void readGeneratedByDragonFightFromNbt(ValueInput input, CallbackInfo ci) {
        this.generatedByDragonFight = input.getBooleanOr("Paper.GeneratedByDragonFight", false);
    }
}
