package io.github.rektroth.whiteout.mixin.mc108513;

import com.llamalad7.mixinextras.sugar.Local;
import com.llamalad7.mixinextras.sugar.ref.LocalRef;
import io.github.rektroth.whiteout.accessors.GeneratedByDragonFightAccessor;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.boss.enderdragon.EndCrystal;
import net.minecraft.world.level.ServerLevelAccessor;
import net.minecraft.world.level.levelgen.feature.EndSpikeFeature;
import net.minecraft.world.level.levelgen.feature.configurations.EndSpikeConfiguration;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

/**
 * End spike feature modifications for MC-108513 patch.
 */
@Mixin(EndSpikeFeature.class)
public class EndSpikeFeatureMixin {
    /**
     * Specifies in the NBT that the crystals on the spikes were generated by the dragon fight.
     * @param level      boilerplate
     * @param random     boilerplate
     * @param config     boilerplate
     * @param spike      boilerplate
     * @param ci         boilerplate
     * @param endCrystal The end crystal.
     */
    @Inject(
        at = @At(
            target = "Lnet/minecraft/world/level/ServerLevelAccessor;addFreshEntity(Lnet/minecraft/world/entity/Entity;)Z",
            value = "INVOKE"),
        method = "placeSpike")
    private void setGeneratedByDragonFight(
            ServerLevelAccessor level,
            RandomSource random,
            EndSpikeConfiguration config,
            EndSpikeFeature.EndSpike spike,
            CallbackInfo ci,
            @Local LocalRef<EndCrystal> endCrystal
    ) {
        GeneratedByDragonFightAccessor g = (GeneratedByDragonFightAccessor)(endCrystal.get());
        g.whiteout$setGeneratedByDragonFight(true);
        endCrystal.set((EndCrystal)g);
    }
}
