# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-snapshot-3
loader_version=0.19.0
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.21.0
maven_group=io.github.rektroth
archives_base_name=whiteout

# Dependencies
lithium_version=mc26.2-0.25.0-fabric
